---
  - name: make sure plugins directory exists
    stat: path=/var/www/wordpress/wp-content/plugins
    register: "pth"

  - debug: msg="plugins directory exists"
    when: pth.stat.isdir is defined and pth.stat.isdir

  - name: make sure mu-plugins directory exists
    file: path=/var/www/wordpress/wp-content/mu-plugins state=directory
    sudo: yes

  - name: copy mu-plugin files
    copy: src=kap_functions.php dest=/var/www/wordpress/wp-content/mu-plugins/kap_functions.php
    sudo: yes

  - name: download plugins from wordpress.org
    get_url: >
      url=https://downloads.wordpress.org/plugin/{{ item }}.zip
      dest=/home/vagrant/{{ item }}.zip
    with_items:
      - wp-admin-ui-customize.1.5.7
      - relative-url.0.0.13
      - types.1.8.10
    sudo: yes

  - name: extract plugins
    unarchive: >
      src=/home/vagrant/{{ item }}.zip
      dest=/var/www/wordpress/wp-content/plugins/
      copy=no
    with_items:
      - wp-admin-ui-customize.1.5.7
      - relative-url.0.0.13
      - types.1.8.10
    sudo: yes

  - name: copy db dump to box
    copy: src=data/wordpress/wordpress-local-{{ backup_date }}.sql dest=/home/vagrant/

  - name: load db dump to wordpress-local.sql
    mysql_db: >
      name={{ db_name }}
      state=import
      target=/vagrant/data/wordpress-local-{{ backup_date }}.sql
    sudo: yes

  - name: copy child theme files
    # grab from GitHub when there is a release
    # get_url: src=katherine-anne.zip dest=/home/vagrant/katherine-anne.zip
    when: "'local' not in group_names"
    sudo: yes

  - name: make sure theme directory exists
    file: >
      path=/var/www/wordpress/wp-content/themes/katherine-anne
      state=directory
      owner=wordpress
      group=wordpress
      recurse=yes
    sudo: yes

  # - name: load child theme
  #   unarchive: >
  #     src=/home/vagrant/katherine-anne.zip
  #     dest=/var/www/wordpress/wp-content/themes/katherine-anne
  #     copy=no
  #   when: "'local' not in group_names"
  #   sudo: yes
  #   notify:
  #     - restart nginx
