---
  - name: update mysql conf for admins
    template: src=home_my.cnf.j2 dest=/home/ubuntu/.my.cnf
    sudo: yes

  - name: create wordpress db
    mysql_db: name={{ db_name }} state=present

  - name: create wordpress db user
    mysql_user: name={{ db_user }} password={{ db_password }} priv={{ db_name }}.*:ALL host='{{ db_host }}' state=present
