---
  - name: set up a wordpress install runnning katherine-anne
    hosts: local
    user: ubuntu  # Vagrantfile overrides for vagrant
    roles:
      - system
      - mysql
      - nginx
      - php-fpm
      - wordpress
      - wp-custom
